# Generated by Django 4.1.4 on 2022-12-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveiapp', '0002_alter_movei_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movei',
            name='img',
            field=models.ImageField(default='gchgfj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
